version: '3.9'

services:
  app:
    build: .
    image: efcore-api-image-${PORT:-50001}
    container_name: sola-erp-api-old-${PORT:-50001}
    restart: always
    ports:
      - "${PORT:-50001}:50001"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
    volumes:
      - /media:/media
